### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by masterzxz** [klept0/MS-Rewards-Farmer#269]
### Before submitting a bug report...

- [x] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [x] I've cleared the sessions folder.

### Branch

develop

### Commit

6cd449a

### Describe the bug

On the latest version of the development branch, I get the following error:

### Copy and paste your error

`←[38;5;39m2025-02-25 09:55:05,713 [INFO] [BING] Starting Desktop Edge Bing searches...←[0m
←[38;5;39m2025-02-25 09:55:12,254 [INFO] [BING] Remaining searches=RemainingSearches(desktop=30, mobile=20)←[0m
←[38;5;226m2025-02-25 09:55:12,517 [WARNING] Error parsing JSON: the JSON object must be str, bytes or bytearray, not NoneType←[0m
←[38;5;196m2025-02-25 09:55:12,517 [ERROR] No valid JSON found in response←[0m
←[38;5;196m2025-02-25 09:55:12,519 [ERROR] Failed to extract JSON from Google Trends response←[0m
←[38;5;196m2025-02-25 09:55:16,212 [ERROR] ←[0m
Traceback (most recent call last):
  File "C:\Scripts\MS-Rewards-Farmer-develop\main.py", line 32, in main
    earned_points = executeBot(currentAccount)
  File "C:\Scripts\MS-Rewards-Farmer-develop\main.py", line 157, in executeBot
    searches.bingSearches()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Scripts\MS-Rewards-Farmer-develop\src\searches.py", line 186, in bingSearches
    self.bingSearch()
    ~~~~~~~~~~~~~~~^^
  File "C:\Scripts\MS-Rewards-Farmer-develop\src\searches.py", line 198, in bingSearch
    rootTerm = list(self.googleTrendsShelf.keys())[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
←[38;5;39m2025-02-25 09:55:16,215 [INFO] [POINTS] Data saved for the next day.←[0m`

### Screenshots

Not shown in browser

### Value of dashboard variable

Not relevant

**Comment by gh0sti** [comment]
I have this error as well

**Comment by FunnyPocketBook** [comment]
I believe this error is tied to the location of the user. I'm in the Netherlands.

The error `Failed to extract JSON from Google Trends response` comes up because `googleTrendsShelf` is empty. This in turn is empty because `self.browser.localeGeo` [here](https://github.com/klept0/MS-Rewards-Farmer/blob/6f11a91ff2ff1fece1d46e2d923e7091da95c0c2/src/searches.py#L68) turns up as `Netherlands` instead of `NL`.  `self.browser.localeGeo` gets its value for the country [here](https://github.com/klept0/MS-Rewards-Farmer/blob/6f11a91ff2ff1fece1d46e2d923e7091da95c0c2/src/browser.py#L224) using Python's built-in `locale.getlocale()`. On Windows, this returns `('English_Netherlands', '1252')`, which explains why the country code passed to the Google Trends search is `Netherlands` and not `NL`. 

To manually set these values, they have to be defined in the [configuration file](https://github.com/klept0/MS-Rewards-Farmer/tree/develop?tab=readme-ov-file#configuration-file). For me, that would be `NL` and `en`

```yaml
# config.yaml
...
browser:
  geolocation: NL # Replace with your country code https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2.
    # Detected by default, can be overridden with command-line arguments.
  language: en # Replace with your language code https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.
    # Detected by default, can be overridden with command-line arguments.
...
```
